### ISSUE TITLE
关于指令输入错误后导致整个bot无法使用

### ISSUE THREAD

**Issue by AtoriUzawa** [Jigsaw111/nonebot_plugin_manager#16]
npm chmod mode nonebot_plugin_setu4 757输入后插件不删除会导致整个bot没反应(我知道指令写错了，但是复制的时候没看清，大佬有啥解决方法吗，怎么才能再次启用)

报错：
Traceback (most recent call last):
  File "bot.py", line 72, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 179, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/utils.py", line 138, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/ubuntu/bot_linux/atri/atri/plugins/nonebot_plugin_manager/__init__.py", line 34, in _
    plugin_manager.update_plugin(
  File "/home/ubuntu/bot_linux/atri/atri/plugins/nonebot_plugin_manager/manager.py", line 115, in update_plugin
    int(self.__plugin_list[p]["mode"][0]) & 4 == 4,
ValueError: invalid literal for int() with base 10: 'm

**Comment by j1g5awi** [comment]
打开机器人目录下的 `/data/plugin_list.yml`，nonebot_plugin_setu4 的 `mode` 改正确
