### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'm'

### ISSUE THREAD

**Issue by AHBYCR** [Jigsaw111/nonebot_plugin_manager#18]
12-08 15:39:38 [SUCCESS] nonebot | OneBot V11 17xxxxxx21 | [message.group.normal]: Message -136xxxx3992 from 3xxxx2660@[群:3xxxxx1x0] "/npm block nonebot_plugin_matcher_block"
12-08 15:39:38 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_matcher_block)
12-08 15:39:38 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "d:\QQbot\JUNEZ\bot.py", line 59, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_manager\manager.py", line 106, in update_plugin
    other = PluginManager().__add_plugin(plugin).__remove_plugin(plugin)
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_manager\manager.py", line 106, in update_plugin
    other = PluginManager().__add_plugin(plugin).__remove_plugin(plugin)
  File "C:\Users\AHBCYR\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_manager\manager.py", line 124, in __add_plugin    int(self.__plugin_list[p]["mode"][0]) & 4 == 4,
ValueError: invalid literal for int() with base 10: 'm'

**Comment by j1g5awi** [comment]
同 #16
