### ISSUE TITLE
与别的插件有冲突

### ISSUE THREAD

**Issue by kexue-z** [Jigsaw111/nonebot_plugin_manager#3]
# nb log

这是发送一条文本触发的两个插件的log

```
08-24 11:08:49 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_puppet, type=message, priority=10, temp=False>
08-24 11:08:49 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 140, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_manager/__init__.py", line 28, in _
    plugin = matcher.module.split(".", maxsplit=1)[0]
AttributeError: module 'nonebot_plugin_puppet' has no attribute 'split'
08-24 11:08:49 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_wordbank, type=message, priority=99, temp=False>
08-24 11:08:49 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 140, in _run_matcher
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_manager/__init__.py", line 28, in _
    plugin = matcher.module.split(".", maxsplit=1)[0]
AttributeError: module 'nonebot_plugin_wordbank' has no attribute 'split'
```

# 软件版本

```
nonebot2                   2.0.0a15
nonebot-plugin-wordbank    1.0.2
nonebot-plugin-manager     0.4.0
nonebot-plugin-puppet      0.1.4
```

# 复现

发送任意的消息就会出现。
并且另外的两个插件也不会正常工作
将 `nonebot-plugin-manager` 关闭后就可以恢复正常

**Comment by j1g5awi** [comment]
这是本插件没有适配 a14 以上版本导致的问题，把 `matcher.module.split(".", maxsplit=1)[0]` 改成 `matcher.plugin_name` 就行了。

**Comment by kexue-z** [comment]
将 `__init__.py` 的 21 行从`matcher.module.split(".", maxsplit=1)[0]`改为 `plugin = matcher.plugin_name` 后出现了
```
08-24 13:45:05 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 140, in _run_matcher
    await asyncio.gather(*coros)
  File "/nonebot/plugins/nonebot_plugin_manager/__init__.py", line 35, in _
    if not plugin_manager.get_plugin(conv=conv, perm=1)[plugin]:
KeyError: '联系管理员'
```

**Comment by kexue-z** [comment]
补充： 
插件是git clone下来的直接放入nb插件目录下运行的，而不是pip下载的
这是超管直接**私聊**bot发送任意消息时的反应，其他插件可以正常运行
但是会出现上述报错 ，本插件的`npm ls` 和 `npm block` 可以正常使用
当使用 `npm block --all` 后想要运行`npm unblock` `npm ls` 指令就会出现
```
08-24 13:59:13 [ERROR] nonebot | Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 140, in _run_matcher
    await asyncio.gather(*coros)
  File "/nonebot/plugins/nonebot_plugin_manager/__init__.py", line 35, in _
    if not plugin_manager.get_plugin(conv=conv, perm=1)[plugin]:
KeyError: '联系管理员'
```
无法重新开启插件

**Comment by j1g5awi** [comment]
打开 bot 目录下的  data/manager/plugin_list.yml ，看下 npm 叫什么名字，删掉对应的部分，把

https://github.com/nonepkg/nonebot-plugin-manager/blob/de0a8259403aad559f45640ada99bb448f488c9e/nonebot_plugin_manager/__init__.py#L30

里的 nonebot_plugin_manager 改成那个名字

我大概知道问题所在了，本地目录加载的插件名称与作为 pip 包加载的名称不一样，导致 npm 把自己屏蔽了。

**Comment by kexue-z** [comment]
data/manager/plugin_list.yml 里的 npm 就叫`nonebot_plugin_manager`
`__init__.py`  30行 也是 `str(p.name): p.name != "nonebot_plugin_manager" and p.matcher `

```yaml
nonebot_plugin_manager:
  group:
    363342330: 4
  mode: '311'
  user: {}
```

```py
    plugin_manager.update_plugin(
        {
            str(p.name): p.name != "nonebot_plugin_manager" and p.matcher
            for p in get_loaded_plugins()
        }
    )
```

**Comment by j1g5awi** [comment]
完蛋，那就是我那段时间脑子抽了写出 bug 了。

**Comment by j1g5awi** [comment]
麻烦把 `plugin_list.yml` 全部发出来下吧（当然群号和 qq 号可以删掉）

**Comment by kexue-z** [comment]
而且我发现。。

 先在群聊中运行 `npm block --all` 后 可以正常停用插件

再私聊bot `npm unblock --all` 后
就可以在这个群里面继**续使用插件** 群聊的停用**不生效**

于是我就可以 `npm unblock --all` 给这个群的所有人重新开启插件

**Comment by kexue-z** [comment]
```yaml
nonebot_hk_reporter:
  group:
    群号: 4
  mode: '755'
  user:
    QQ号: 5
nonebot_plugin_apscheduler:
  group:
    群号: 4
  mode: '311'
  user:
    QQ号: 5
nonebot_plugin_cocdicer:
  group:
    群号: 4
  mode: '755'
  user:
    QQ号: 5
nonebot_plugin_gamedraw:
  group:
    群号: 4
  mode: '755'
  user:
    QQ号: 5
nonebot_plugin_manager:
  group:
    群号: 4
  mode: '311'
  user:
    QQ号: 5
nonebot_plugin_picsearcher:
  group:
    群号: 4
  mode: '755'
  user:
    QQ号: 5
nonebot_plugin_puppet:
  group:
    群号: 4
  mode: '755'
  user:
    QQ号: 5
nonebot_plugin_test:
  group:
    群号: 4
  mode: '311'
  user:
    QQ号: 5
nonebot_plugin_wordbank:
  group:
    群号: 4
  mode: '755'
  user:
    QQ号: 5
```

**Comment by j1g5awi** [comment]
![image](https://user-images.githubusercontent.com/50312681/130571074-350311dd-48d9-41e9-aec1-2c90440c8358.png)

你给 `plugin_name` 自定义了，导致 nb 识别不出来 Matcher 属于哪个插件，就像： nonebot/nonebot2#502 一样。

npm 依赖于 nb 的插件识别机制，所以就出错了，你只要把这个自定义的 `__plugin_name__` 删除 npm 就能正常工作了。

**Comment by kexue-z** [comment]
好！谢谢佬！
