### ISSUE TITLE
请问可以排除拦截某个插件吗

### ISSUE THREAD

**Issue by Bearlele** [Jigsaw111/nonebot_plugin_manager#8]
插件名status 确认已启用 并给予了777权限后执行/ping依然报错

```py
# __init__.py：
ping = IsSurvive().on_command("/ping")

data_source.py：
@ping.handle()
async def _ping():
    await ping.finish("pang!")
```

错误信息：

```
ATRI | 04-19 11:24:36 | SUCCESS nonebot >> ONEBOT V11 275*****85 | [message.group.normal]: Message 233817813 from 258*****46@[群:474****82] "npm chmod 777 status"
ATRI | 04-19 11:24:36 | INFO nonebot >> Event will be handled by <Matcher from nonebot_plugin_manager, type=message, priority=1, temp=False>
ATRI | 04-19 11:24:36 | INFO nonebot >> Matcher <Matcher from nonebot_plugin_manager, type=message, priority=1, temp=False> running complete
ATRI | 04-19 11:24:45 | SUCCESS nonebot >> ONEBOT V11 275*****85 | [message.group.normal]: Message -460561440 from 2587342146@[群:474****82] "/ping"
ATRI | 04-19 11:24:45 | INFO nonebot >> Event will be handled by <Matcher from 状态, type=message, priority=1, temp=False>
ATRI | 04-19 11:24:45 | ERROR nonebot >> Error when running RunPreProcessors. Running cancelled!
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fc53f827820>: <Task finished name='Task-6806' coro=<_command() done, defined at /usr/local/lib/pyth...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fc51b7aed30>
          │            │        │    │      └ {'_prefix': {'command': ('/ping',), 'raw_command': '/ping', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1650338684, self_id=275*****85, post_type='message', sub_type='normal', user_id=258*****46, message_ty...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fc51b5d10a0>
          │            └ <Matcher from 状态, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fc53f6c2040>

> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 185, in _run_matcher
    await asyncio.gather(*coros)
          │       │       └ [<coroutine object _run_coro_with_catch at 0x7fc51b595e40>]
          │       └ <function gather at 0x7fc5404c6f70>
          └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 115, in _run_coro_with_catch
    return await coro
                 └ <coroutine object Dependent.__call__ at 0x7fc51b5957c0>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'matcher': <Matcher from 状态, type=message, priority=1, temp=False>, 'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x...
                 │    └ <function _ at 0x7fc53e1f2d30>
                 └ <Dependent call=<function _ at 0x7fc53e1f2d30>, params=[ModelField(name='matcher', type=Matcher, required=True), ModelField(n...

  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_manager/__init__.py", line 48, in _
    if not plugin_manager.get_plugin(conv=conv, perm=1)[plugin]:
           │              │               │             └ None
           │              │               └ {'user': [258*****46], 'group': [474****82]}
           │              └ <function PluginManager.get_plugin at 0x7fc53ec238b0>
           └ <nonebot_plugin_manager.manager.PluginManager object at 0x7fc51b7b9490>

KeyError: None
```

**Comment by Bearlele** [comment]
大概发现是什么问题了
使用npm ls命令看是开启的
但是查看plugin_list.yml是false的
手动改成true也无效
使用npm unblock status启用提示成功 实际还是false

**Comment by j1g5awi** [comment]
从你的 Matcher 获取不到插件名称，我怀疑是和其他插件冲突了。

更详细点，ATRI 的 Service 篡改了 NoneBot2 的 Matcher 机制，所以获取不到插件名称。

**Comment by Bearlele** [comment]
明白了 感谢指点
